
export const GET_TABLE_SUCCESS = "GET_TABLE_SUCCESS";
export const GET_TABLE_FAIL = "GET_TABLE_FAIL";
export const GET_CURRENT_INFO = "GET_CURRENT_INFO";
export const CONNECTED_SOCKET = "CONNECTED_SOCKET";
export const DIS_CONNECTED_SOCKET = "DIS_CONNECTED_SOCKET";
